### ISSUE TITLE
open for hactoberfest

### ISSUE THREAD

**Issue by navnit0707** [navnit0707/PythonPractice#1]
Update The readme file according to question added.....

**Comment by 19-ade** [comment]
Hey I'm willing to help . can you assign me this ? thanks

**Comment by pyprakhar** [comment]
Hey , Please assign me this task i will do well

**Comment by navnit0707** [comment]
Yes you are assigned

**Comment by 19-ade** [comment]
Hey I sent it . the PR.

**Comment by Rimjhim20** [comment]
Hey!Assigned it to me.

**Comment by Rimjhim20** [comment]
Hey! assigned it to me. Ty

**Comment by onlykingKD** [comment]
Assign me 🤞

**Comment by Niyati3031** [comment]
Can you assign me this please @navnit0707

**Comment by nikhil2222** [comment]
Hi , I can fix this issue , Assign me

**Comment by navnit0707** [comment]
Ok #assigned

**Comment by navnit0707** [comment]
Ok

**Comment by johnjoel2001** [comment]
Can u assign me pls?

**Comment by navnit0707** [comment]
Ok

**Comment by rounit08** [comment]
Can I take this?

**Comment by navnit0707** [comment]
Yes
